$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json

name: blue
endpoint_name: loan-endpoint-v4

model: azureml:loan-approval-model@latest

code_configuration:
  code: ./src/azuremlapp/utils
  scoring_script: score.py

environment:
  conda_file: conda.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

instance_type: Standard_DS3_v2
instance_count: 1