name: Loan MLOps Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn==1.7.2 joblib python-dotenv

      - name: Run training
        run: |
          python src/azuremlapp/utils/train.py